// <auto-generated />
using DersKayitSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DersKayitSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231207091842_Ders")]
    partial class Ders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DersKayitSistemi.Models.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DersKodu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DersKontenjan")
                        .HasColumnType("int");

                    b.Property<int>("DersKredi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dersler");
                });
#pragma warning restore 612, 618
        }
    }
}
